version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "attributeerror"
    commit-message:
      prefix: "github-actions"

  # Maintain Docker image versions
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "attributeerror"
    commit-message:
      prefix: "docker"