name: Build & push Docker image

on:
  workflow_call:
    inputs:
      package-name:
        type: string
        required: true

jobs:
  build:
    if: |
      github.triggering_actor != 'dependabot[bot]'
      && contains(fromJSON('["fix", "feat", "chore", "test", "build", "ci", "perf", "refactor", "revert", "style"]'), github.event.head_commit.message)
      && !contains(github.event.head_commit.message, '!skip!')
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: "Setup NodeJS"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Build & push the Docker image
        run: |
          docker build --file Dockerfile --tag ghcr.io/attributeerror/${{ inputs.package-name }}:$(git log --format="%h" -n 1) .
          docker push ghcr.io/attributeerror/${{ inputs.package-name }}:$(git log --format="%h" -n 1)